# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-01 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchID', models.CharField(max_length=60)),
                ('RowNumInFile', models.IntegerField()),
                ('TxnID', models.CharField(max_length=100)),
                ('AccountID', models.CharField(max_length=50)),
                ('TxnTypeCode', models.CharField(max_length=50)),
                ('PaymentType', models.CharField(default=None, max_length=50)),
                ('Channel', models.CharField(default=None, max_length=50)),
                ('IsForeignTxn', models.CharField(max_length=1)),
                ('IsCashTxn', models.CharField(max_length=1)),
                ('CashInAmount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('CashOutAmount', models.DecimalField(decimal_places=2, default=None, max_digits=19)),
                ('TransferInAmount', models.DecimalField(decimal_places=2, default=None, max_digits=19)),
                ('TransferOutAmount', models.DecimalField(decimal_places=2, default=None, max_digits=19)),
                ('Amount', models.DecimalField(decimal_places=2, default=None, max_digits=19)),
                ('BaseCurrency', models.CharField(default=None, max_length=10)),
                ('CheckNumber', models.CharField(default=None, max_length=150)),
                ('EnteredDate', models.DateField(default=None)),
                ('EffectiveDate', models.DateField(default=datetime.date.today)),
                ('ReversalDate', models.DateField(default=None)),
                ('OrginalITxnCode', models.CharField(default=None, max_length=50)),
                ('ApplicationID', models.CharField(default=None, max_length=20)),
                ('SourceSystem', models.CharField(max_length=20)),
                ('UserDefined1', models.CharField(default=None, max_length=255)),
                ('UserDefined2', models.CharField(default=None, max_length=255)),
                ('UserDefined3', models.CharField(default=None, max_length=255)),
                ('UserDefined4', models.CharField(default=None, max_length=255)),
                ('UserDefined5', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
